https:
  jks:
    alias: "![r65YgZ3yoLLB5HMHN1EK9RHpSY/k5g+i]"
    path: "![FI/b5VK/S0x/LSxTawXgwHY5+BVcsCIcb/ZBS/7cz9S2O5wBhJTklw==]"
    passphrase: "![r65YgZ3yoLLB5HMHN1EK9RHpSY/k5g+i]"
    password: "![r65YgZ3yoLLB5HMHN1EK9RHpSY/k5g+i]"